
// var data = {
//     "cluster_names": ['Cluster_4', 'Cluster_7', 'Cluster_2'],
//     "cluster_values": [287, 216, 211],
//     "hubs_cluster_id": ['VK', 'OK', 'Fb'], 
//     "hubs_cluster_values": [11, 12, 8],
//     "cluster_parent": ['Cluster_4', 'Cluster_7', 'Cluster_2']
//     }

var data = {"cluster_names": ["Cluster_4",
"Cluster_7",
"Cluster_2",
"Cluster_5",
"Cluster_0",
"Cluster_3",
"Cluster_1",
"Cluster_6"],
"cluster_values": [287, 216, 211, 141, 128, 111, 68, 4],
"hubs_cluster_id": [["telegra.ph",
 "vk.com",
 "zen.yandex.ru",
 "ok.ru",
 "youtube.com",
 "telegram.org",
 "apple.com",
 "facebook.com",
 "instagram.com",
 "banki.ru",
 "pikabu.ru",
 "twitter.com",
 "mirtesen.ru",
 "smart-lab.ru",
 "mfd.ru",
 "hr-portal.ru",
 "sravni.ru",
 "nerab.ru",
 "profinance.ru",
 "play.google.com",
 "q.yandex.ru"],
["vk.com",
 "irecommend.ru",
 "telegram.org",
 "awd.ru",
 "banki.ru",
 "zen.yandex.ru",
 "instagram.com",
 "ok.ru",
 "sravni.ru",
 "otzovik.com",
 "play.google.com",
 "asn-news.ru",
 "flamp.ru",
 "maps.yandex.ru",
 "pikabu.ru",
 "vc.ru",
 "twitter.com",
 "e1.ru",
 "otzyv.ru",
 "glav.su",
 "smart-lab.ru",
 "telegra.ph",
 "youtube.com",
 "2gis.ru",
 "apple.com",
 "facebook.com"],
["baby.ru",
 "vk.com",
 "instagram.com",
 "telegram.org",
 "banki.ru",
 "youtube.com",
 "smart-lab.ru",
 "pikabu.ru",
 "play.google.com",
 "otvet.mail.ru",
 "facebook.com",
 "twitter.com",
 "awd.ru",
 "sravni.ru",
 "lenta.ru",
 "mfd.ru",
 "ok.ru",
 "forum.bits.media",
 "maps.yandex.ru",
 "littleone.ru",
 "zen.yandex.ru",
 "apple.com"],
["vk.com",
 "banki.ru",
 "sravni.ru",
 "facebook.com",
 "telegram.org",
 "instagram.com",
 "ok.ru",
 "telegra.ph",
 "zen.yandex.ru",
 "youtube.com"],
["apple.com",
 "play.google.com",
 "banki.ru",
 "sravni.ru",
 "profinance.ru",
 "instagram.com",
 "vk.com",
 "pravda-sotrudnikov.ru",
 "ocompanii.com"],
["instagram.com",
 "telegram.org",
 "banki.ru",
 "vk.com",
 "youtube.com",
 "forum.onliner.by",
 "facebook.com",
 "sravni.ru",
 "irecommend.ru",
 "ok.ru",
 "rutube.ru",
 "play.google.com",
 "zen.yandex.ru"],
["telegram.org", "vk.com", "instagram.com", "ok.ru"],
["vk.com"]],
"hubs_cluster_values": [[6,
 137,
 11,
 12,
 13,
 56,
 1,
 6,
 20,
 11,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1],
[57,
 1,
 45,
 1,
 39,
 9,
 13,
 13,
 7,
 5,
 6,
 1,
 1,
 1,
 3,
 2,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1],
[2, 135, 11, 12, 7, 3, 3, 3, 7, 1, 5, 8, 1, 2, 1, 3, 1, 1, 1, 1, 1, 2],
[87, 1, 3, 3, 22, 17, 5, 1, 1, 1],
[10, 63, 42, 4, 1, 2, 2, 3, 1],
[6, 24, 11, 58, 2, 1, 1, 1, 1, 3, 1, 1, 1],
[21, 34, 8, 5],
[4]],
"cluster_parent": [["Cluster_4",
 "Cluster_4",
 "Cluster_4",
 "Cluster_4",
 "Cluster_4",
 "Cluster_4",
 "Cluster_4",
 "Cluster_4",
 "Cluster_4",
 "Cluster_4",
 "Cluster_4",
 "Cluster_4",
 "Cluster_4",
 "Cluster_4",
 "Cluster_4",
 "Cluster_4",
 "Cluster_4",
 "Cluster_4",
 "Cluster_4",
 "Cluster_4",
 "Cluster_4"],
["Cluster_7",
 "Cluster_7",
 "Cluster_7",
 "Cluster_7",
 "Cluster_7",
 "Cluster_7",
 "Cluster_7",
 "Cluster_7",
 "Cluster_7",
 "Cluster_7",
 "Cluster_7",
 "Cluster_7",
 "Cluster_7",
 "Cluster_7",
 "Cluster_7",
 "Cluster_7",
 "Cluster_7",
 "Cluster_7",
 "Cluster_7",
 "Cluster_7",
 "Cluster_7",
 "Cluster_7",
 "Cluster_7",
 "Cluster_7",
 "Cluster_7",
 "Cluster_7"],
["Cluster_2",
 "Cluster_2",
 "Cluster_2",
 "Cluster_2",
 "Cluster_2",
 "Cluster_2",
 "Cluster_2",
 "Cluster_2",
 "Cluster_2",
 "Cluster_2",
 "Cluster_2",
 "Cluster_2",
 "Cluster_2",
 "Cluster_2",
 "Cluster_2",
 "Cluster_2",
 "Cluster_2",
 "Cluster_2",
 "Cluster_2",
 "Cluster_2",
 "Cluster_2",
 "Cluster_2"],
["Cluster_5",
 "Cluster_5",
 "Cluster_5",
 "Cluster_5",
 "Cluster_5",
 "Cluster_5",
 "Cluster_5",
 "Cluster_5",
 "Cluster_5",
 "Cluster_5"],
["Cluster_0",
 "Cluster_0",
 "Cluster_0",
 "Cluster_0",
 "Cluster_0",
 "Cluster_0",
 "Cluster_0",
 "Cluster_0",
 "Cluster_0"],
["Cluster_3",
 "Cluster_3",
 "Cluster_3",
 "Cluster_3",
 "Cluster_3",
 "Cluster_3",
 "Cluster_3",
 "Cluster_3",
 "Cluster_3",
 "Cluster_3",
 "Cluster_3",
 "Cluster_3",
 "Cluster_3"],
["Cluster_1", "Cluster_1", "Cluster_1", "Cluster_1"],
["Cluster_6"]]}

var data_chart = []
const color = ["#75E492", "#e987cf", "#75C6E4", "#9375E4", "#e49375"];

for (i = 0; i < data.cluster_names.length; i++) {
    data_chart.push({
            id: data.cluster_names[i],
            name: data.cluster_names[i],
            value: data.cluster_values[i],
            color: color[0],
            })}

for (i = 0; i < data.hubs_cluster_id.length; i++) {
    for (j = 0; j < data.hubs_cluster_id[i].length; j++) {
        data_chart.push({
            id: data.hubs_cluster_id[i][j],
            name: data.hubs_cluster_id[i][j],
            value: data.hubs_cluster_values[i][j],
            parent: data.cluster_parent[i][j],
            })
    }
    }

console.log(data_chart);

// [
//     {
//         id: "Central",
//         name: "Central",
//         value: 378148,
//         color: color[0]
//     },
//     {
//         id: "Naitasiri",
//         name: "Naitasiri",
//         value: 177678,
//         parent: "Central"
//     },
//     {
//         id: "Namosi",
//         name: "Namosi",
//         value: 7871,
//         parent: "Central"
//     },
//     {
//         id: "Rewa",
//         name: "Rewa",
//         value: 108016,
//         parent: "Central"
//     },
//     {
//         id: "Serua",
//         name: "Serua",
//         value: 20031,
//         parent: "Central"
//     },